// <auto-generated />
namespace ARM_Hotel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class photo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(photo));
        
        string IMigrationMetadata.Id
        {
            get { return "202205141958190_photo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
