// <auto-generated />
namespace ARM_Hotel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class anot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(anot));
        
        string IMigrationMetadata.Id
        {
            get { return "202203300949541_anot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
